---

- set_fact: ansible_distribution_major_version=6
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"
  tags: ['bitbucket']

- set_fact: ansible_distribution_major_version=7
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  tags: ['bitbucket']

- import_tasks: install.yml
  tags: ['bitbucket', 'bitbucket_install']

- import_tasks: configure.yml
  tags: ['bitbucket', 'bitbucket_configure']

- import_tasks: service.yml
  tags: ['bitbucket', 'bitbucket_service']

- import_tasks: backup.yml
  tags: ['bitbucket', 'bitbucket_backup']

- import_tasks: mysql.yml
  tags: ['bitbucket', 'bitbucket_mysql']

- name: atlassian-bitbucket | wait for server to start up
  wait_for:
    port: 7990
    timeout: 300
  when: bitbucket_wait_for_server_startup
  tags: ['bitbucket']

- name: atlassian-bitbucket | wait for server to initialize
  wait_for:
    port: 7999
    timeout: 300
  when: bitbucket_wait_for_server_startup
  tags: ['bitbucket']
