---
- name: get bitbucket config info
  stat:
    path: "{{ bitbucket_data_dir }}/shared/bitbucket.properties"
    follow: yes
  register: bitbucket_config_info

- debug:
    var: bitbucket_config_info
